2022-01-15 15:45:50,161 INFO    Thread-22 :23868 [wandb_setup.py:_flush():71] setting env: {'project': 'Amazon-Reviews', 'entity': 'ewebid', 'root_dir': '/Users/ewelina/Desktop/MLOps_Amazon_review_project', 'run_id': '3hmcitc3', 'sweep_param_path': '/Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/sweep-y32fxp96/config-3hmcitc3.yaml', 'sweep_id': 'y32fxp96'}
2022-01-15 15:45:50,161 INFO    Thread-22 :23868 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 15:45:50,162 INFO    Thread-22 :23868 [wandb_init.py:_log_setup():371] Logging user logs to /Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/run-20220115_154550-3hmcitc3/logs/debug.log
2022-01-15 15:45:50,162 INFO    Thread-22 :23868 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/run-20220115_154550-3hmcitc3/logs/debug-internal.log
2022-01-15 15:45:50,163 INFO    Thread-22 :23868 [wandb_init.py:init():404] calling init triggers
2022-01-15 15:45:50,163 INFO    Thread-22 :23868 [wandb_init.py:init():409] wandb.init called with sweep_config: {'batch_size': 150, 'drop_out': 0.15, 'epochs': 5, 'lr': 0.01, 'optimizer': 'sgd'}
config: {}
2022-01-15 15:45:50,163 INFO    Thread-22 :23868 [wandb_init.py:init():460] starting backend
2022-01-15 15:45:50,163 INFO    Thread-22 :23868 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 15:45:50,170 INFO    Thread-22 :23868 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 15:45:50,176 INFO    Thread-22 :23868 [backend.py:ensure_launched():221] started backend process with pid: 24034
2022-01-15 15:45:50,182 INFO    Thread-22 :23868 [wandb_init.py:init():469] backend started and connected
2022-01-15 15:45:50,185 INFO    Thread-22 :23868 [wandb_run.py:_config_callback():956] config_cb None None {'batch_size': 150, 'drop_out': 0.15, 'epochs': 5, 'lr': 0.01, 'optimizer': 'sgd'}
2022-01-15 15:45:50,189 INFO    Thread-22 :23868 [wandb_init.py:init():533] updated telemetry
2022-01-15 15:45:50,229 INFO    Thread-22 :23868 [wandb_init.py:init():563] communicating current version
2022-01-15 15:45:53,473 INFO    Thread-22 :23868 [wandb_init.py:init():568] got version response 
2022-01-15 15:45:53,473 INFO    Thread-22 :23868 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 15:45:53,798 INFO    Thread-22 :23868 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 15:45:58,809 INFO    Thread-22 :23868 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 15:45:58,810 INFO    Thread-22 :23868 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 15:45:58,810 INFO    Thread-22 :23868 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 15:45:58,811 ERROR   Thread-22 :23868 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-01-15 15:45:58,811 INFO    Thread-22 :23868 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 15:46:03,983 INFO    Thread-22 :23868 [wandb_run.py:finish():1457] finishing run ewebid/Amazon-Reviews/3hmcitc3
2022-01-15 15:46:03,984 INFO    Thread-22 :23868 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-15 15:46:03,984 INFO    Thread-22 :23868 [wandb_run.py:_restore():1752] restore
2022-01-15 15:46:03,995 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:46:04,104 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:46:04,455 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:46:04,863 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:46:04,967 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:46:05,071 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:46:05,184 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:46:05,290 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:46:05,398 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:05,502 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:05,607 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:05,716 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:05,826 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:05,931 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:06,567 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:46:07,358 INFO    Thread-22 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}
local_info {
}

2022-01-15 15:46:08,643 INFO    Thread-22 :23868 [wandb_run.py:_append_files():2180] logging synced files
