2022-01-15 15:44:22,520 INFO    Thread-2  :23868 [wandb_setup.py:_flush():71] setting env: {'project': 'Amazon-Reviews', 'entity': 'ewebid', 'root_dir': '/Users/ewelina/Desktop/MLOps_Amazon_review_project', 'sweep_id': 'y32fxp96', 'run_id': 'g4gin4m4', 'sweep_param_path': '/Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/sweep-y32fxp96/config-g4gin4m4.yaml'}
2022-01-15 15:44:22,521 INFO    Thread-2  :23868 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 15:44:22,521 INFO    Thread-2  :23868 [wandb_init.py:_log_setup():371] Logging user logs to /Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/run-20220115_154422-g4gin4m4/logs/debug.log
2022-01-15 15:44:22,521 INFO    Thread-2  :23868 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/run-20220115_154422-g4gin4m4/logs/debug-internal.log
2022-01-15 15:44:22,522 INFO    Thread-2  :23868 [wandb_init.py:init():404] calling init triggers
2022-01-15 15:44:22,522 INFO    Thread-2  :23868 [wandb_init.py:init():409] wandb.init called with sweep_config: {'batch_size': 250, 'drop_out': 0.25, 'epochs': 5, 'lr': 0.01, 'optimizer': 'adam'}
config: {}
2022-01-15 15:44:22,522 INFO    Thread-2  :23868 [wandb_init.py:init():460] starting backend
2022-01-15 15:44:22,522 INFO    Thread-2  :23868 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 15:44:22,544 INFO    Thread-2  :23868 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 15:44:22,569 INFO    Thread-2  :23868 [backend.py:ensure_launched():221] started backend process with pid: 23877
2022-01-15 15:44:22,574 INFO    Thread-2  :23868 [wandb_init.py:init():469] backend started and connected
2022-01-15 15:44:22,579 INFO    Thread-2  :23868 [wandb_run.py:_config_callback():956] config_cb None None {'batch_size': 250, 'drop_out': 0.25, 'epochs': 5, 'lr': 0.01, 'optimizer': 'adam'}
2022-01-15 15:44:22,587 INFO    Thread-2  :23868 [wandb_init.py:init():533] updated telemetry
2022-01-15 15:44:22,662 INFO    Thread-2  :23868 [wandb_init.py:init():563] communicating current version
2022-01-15 15:44:24,927 INFO    Thread-2  :23868 [wandb_init.py:init():568] got version response 
2022-01-15 15:44:24,927 INFO    Thread-2  :23868 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 15:44:25,268 INFO    Thread-2  :23868 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 15:44:30,273 INFO    Thread-2  :23868 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 15:44:30,274 INFO    Thread-2  :23868 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 15:44:30,274 INFO    Thread-2  :23868 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 15:44:30,275 ERROR   Thread-2  :23868 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-01-15 15:44:30,281 INFO    Thread-2  :23868 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 15:44:33,721 INFO    Thread-2  :23868 [wandb_run.py:finish():1457] finishing run ewebid/Amazon-Reviews/g4gin4m4
2022-01-15 15:44:33,722 INFO    Thread-2  :23868 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-15 15:44:33,725 INFO    Thread-2  :23868 [wandb_run.py:_restore():1752] restore
2022-01-15 15:44:33,732 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:44:34,195 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:44:34,307 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:44:34,414 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:44:34,520 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:44:34,632 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18065
}

2022-01-15 15:44:34,734 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11921
  total_bytes: 18065
}

2022-01-15 15:44:34,840 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:34,943 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:35,051 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:35,160 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:35,267 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:35,376 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:35,992 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}

2022-01-15 15:44:36,627 INFO    Thread-2  :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18065
  total_bytes: 18065
}
local_info {
}

2022-01-15 15:44:37,795 INFO    Thread-2  :23868 [wandb_run.py:_append_files():2180] logging synced files
