2022-01-17 18:42:25,470 INFO    Thread-2  :17413 [wandb_setup.py:_flush():71] setting env: {'entity': 'amazonproject', 'project': 'Amazon-Reviews', 'root_dir': '/Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project', 'sweep_id': '7yvyli1n', 'run_id': 'ixvtp1md', 'sweep_param_path': '/Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project/wandb/sweep-7yvyli1n/config-ixvtp1md.yaml'}
2022-01-17 18:42:25,471 INFO    Thread-2  :17413 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 18:42:25,471 INFO    Thread-2  :17413 [wandb_init.py:_log_setup():371] Logging user logs to /Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project/wandb/run-20220117_184225-ixvtp1md/logs/debug.log
2022-01-17 18:42:25,471 INFO    Thread-2  :17413 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project/wandb/run-20220117_184225-ixvtp1md/logs/debug-internal.log
2022-01-17 18:42:25,472 INFO    Thread-2  :17413 [wandb_init.py:init():404] calling init triggers
2022-01-17 18:42:25,472 INFO    Thread-2  :17413 [wandb_init.py:init():409] wandb.init called with sweep_config: {'batch_size': 200, 'drop_out': 0.35, 'epochs': 5, 'lr': 0.001, 'optimizer': 'sgd'}
config: {}
2022-01-17 18:42:25,472 INFO    Thread-2  :17413 [wandb_init.py:init():460] starting backend
2022-01-17 18:42:25,472 INFO    Thread-2  :17413 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-01-17 18:42:25,495 INFO    Thread-2  :17413 [backend.py:ensure_launched():216] starting backend process...
2022-01-17 18:42:25,509 INFO    Thread-2  :17413 [backend.py:ensure_launched():221] started backend process with pid: 17421
2022-01-17 18:42:25,511 INFO    Thread-2  :17413 [wandb_init.py:init():469] backend started and connected
2022-01-17 18:42:25,515 INFO    Thread-2  :17413 [wandb_run.py:_config_callback():956] config_cb None None {'batch_size': 200, 'drop_out': 0.35, 'epochs': 5, 'lr': 0.001, 'optimizer': 'sgd'}
2022-01-17 18:42:25,518 INFO    Thread-2  :17413 [wandb_init.py:init():533] updated telemetry
2022-01-17 18:42:25,545 INFO    Thread-2  :17413 [wandb_init.py:init():563] communicating current version
2022-01-17 18:42:26,511 INFO    Thread-2  :17413 [wandb_init.py:init():568] got version response 
2022-01-17 18:42:26,511 INFO    Thread-2  :17413 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-17 18:42:26,731 INFO    Thread-2  :17413 [wandb_init.py:init():606] starting run threads in backend
2022-01-17 18:42:28,324 INFO    Thread-2  :17413 [wandb_run.py:_console_start():1810] atexit reg
2022-01-17 18:42:28,324 INFO    Thread-2  :17413 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-17 18:42:28,324 INFO    Thread-2  :17413 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-17 18:42:28,325 ERROR   Thread-2  :17413 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/Users/augustehlers/miniconda3/envs/MLOPs_project/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/Users/augustehlers/miniconda3/envs/MLOPs_project/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/Users/augustehlers/miniconda3/envs/MLOPs_project/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/Users/augustehlers/miniconda3/envs/MLOPs_project/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/Users/augustehlers/miniconda3/envs/MLOPs_project/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-01-17 18:42:28,326 INFO    Thread-2  :17413 [wandb_init.py:init():633] run started, returning control to user process
2022-01-17 18:42:35,981 INFO    MainThread:17413 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-17 18:42:35,983 INFO    MainThread:17413 [wandb_run.py:_restore():1752] restore
