2022-01-15 15:45:28,839 INFO    Thread-17 :23868 [wandb_setup.py:_flush():71] setting env: {'project': 'Amazon-Reviews', 'entity': 'ewebid', 'root_dir': '/Users/ewelina/Desktop/MLOps_Amazon_review_project', 'run_id': 'tyzrtc5g', 'sweep_param_path': '/Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/sweep-y32fxp96/config-tyzrtc5g.yaml', 'sweep_id': 'y32fxp96'}
2022-01-15 15:45:28,840 INFO    Thread-17 :23868 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-15 15:45:28,840 INFO    Thread-17 :23868 [wandb_init.py:_log_setup():371] Logging user logs to /Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/run-20220115_154528-tyzrtc5g/logs/debug.log
2022-01-15 15:45:28,840 INFO    Thread-17 :23868 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/ewelina/Desktop/MLOps_Amazon_review_project/wandb/run-20220115_154528-tyzrtc5g/logs/debug-internal.log
2022-01-15 15:45:28,840 INFO    Thread-17 :23868 [wandb_init.py:init():404] calling init triggers
2022-01-15 15:45:28,840 INFO    Thread-17 :23868 [wandb_init.py:init():409] wandb.init called with sweep_config: {'batch_size': 150, 'drop_out': 0.35, 'epochs': 5, 'lr': 0.01, 'optimizer': 'sgd'}
config: {}
2022-01-15 15:45:28,841 INFO    Thread-17 :23868 [wandb_init.py:init():460] starting backend
2022-01-15 15:45:28,841 INFO    Thread-17 :23868 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-15 15:45:28,845 INFO    Thread-17 :23868 [backend.py:ensure_launched():216] starting backend process...
2022-01-15 15:45:28,850 INFO    Thread-17 :23868 [backend.py:ensure_launched():221] started backend process with pid: 23998
2022-01-15 15:45:28,855 INFO    Thread-17 :23868 [wandb_init.py:init():469] backend started and connected
2022-01-15 15:45:28,859 INFO    Thread-17 :23868 [wandb_run.py:_config_callback():956] config_cb None None {'batch_size': 150, 'drop_out': 0.35, 'epochs': 5, 'lr': 0.01, 'optimizer': 'sgd'}
2022-01-15 15:45:28,865 INFO    Thread-17 :23868 [wandb_init.py:init():533] updated telemetry
2022-01-15 15:45:28,919 INFO    Thread-17 :23868 [wandb_init.py:init():563] communicating current version
2022-01-15 15:45:32,249 INFO    Thread-17 :23868 [wandb_init.py:init():568] got version response 
2022-01-15 15:45:32,250 INFO    Thread-17 :23868 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-15 15:45:32,685 INFO    Thread-17 :23868 [wandb_init.py:init():606] starting run threads in backend
2022-01-15 15:45:37,695 INFO    Thread-17 :23868 [wandb_run.py:_console_start():1810] atexit reg
2022-01-15 15:45:37,696 INFO    Thread-17 :23868 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-15 15:45:37,696 INFO    Thread-17 :23868 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-15 15:45:37,697 ERROR   Thread-17 :23868 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-01-15 15:45:37,697 INFO    Thread-17 :23868 [wandb_init.py:init():633] run started, returning control to user process
2022-01-15 15:45:42,298 INFO    Thread-17 :23868 [wandb_run.py:finish():1457] finishing run ewebid/Amazon-Reviews/tyzrtc5g
2022-01-15 15:45:42,301 INFO    Thread-17 :23868 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-15 15:45:42,303 INFO    Thread-17 :23868 [wandb_run.py:_restore():1752] restore
2022-01-15 15:45:42,318 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:45:42,710 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-01-15 15:45:43,680 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18064
}

2022-01-15 15:45:43,782 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18064
}

2022-01-15 15:45:43,889 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18064
}

2022-01-15 15:45:43,991 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18064
}

2022-01-15 15:45:44,106 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 18064
}

2022-01-15 15:45:44,216 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:44,320 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:44,427 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:44,535 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:44,639 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:44,746 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:45,266 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}

2022-01-15 15:45:46,238 INFO    Thread-17 :23868 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18064
  total_bytes: 18064
}
local_info {
}

2022-01-15 15:45:47,484 INFO    Thread-17 :23868 [wandb_run.py:_append_files():2180] logging synced files
